# Generated by Django 4.1.6 on 2023-02-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appnews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
